-- ==============================================================================
-- PickingUp CRM - Esfuerzo de Consolidación de Esquema de Base de Datos
-- ==============================================================================
--
-- INSTRUCCIONES:
-- 1. Pegá aquí el contenido de tus tablas, funciones, triggers y políticas (RLS).
-- 2. Podés obtener esto desde Supabase -> SQL Editor -> "Dump" o exportando el esquema.
-- 3. Una vez que pegues el contenido, yo podré analizarlo para proponerte:
--    - Optimizaciones de índices para velocidad.
--    - Mejoras en la estructura de relaciones (Foreign Keys).
--    - Refactorización de Triggers y Funciones para mejor rendimiento.
--    - Revisión de seguridad en políticas RLS.
-- ==============================================================================

-- [PEGAR SQL AQUÍ ABAJO]

create table public.actividades (
  id bigserial not null,
  cliente_id bigint not null,
  fecha timestamp with time zone not null default now(),
  descripcion text not null,
  usuario text null,
  user_id uuid null,
  empresa_id uuid null,
  constraint actividades_pkey primary key (id),
  constraint actividades_cliente_id_fkey foreign KEY (cliente_id) references clientes (id) on delete CASCADE,
  constraint actividades_empresa_id_fkey foreign KEY (empresa_id) references empresas (id)
) TABLESPACE pg_default;

create index IF not exists actividades_cliente_fecha_idx on public.actividades using btree (cliente_id, fecha desc) TABLESPACE pg_default;

create index IF not exists actividades_usuario_idx on public.actividades using btree (usuario) TABLESPACE pg_default;

create trigger trg_actividades_ultima_actividad_del
after DELETE on actividades for EACH row
execute FUNCTION refresh_ultima_actividad ();

create trigger trg_actividades_ultima_actividad_ins
after INSERT
or
update on actividades for EACH row
execute FUNCTION refresh_ultima_actividad ();

create trigger trg_bump_ultima_actividad_cliente
after INSERT on actividades for EACH row
execute FUNCTION bump_ultima_actividad_cliente ();

create trigger trg_fill_activity_user BEFORE INSERT on actividades for EACH row
execute FUNCTION fill_activity_user ();

create table public.actividades_consumidores (
  id bigserial not null,
  consumidor_id bigint not null,
  fecha timestamp with time zone not null default now(),
  descripcion text not null,
  usuario text null,
  user_id uuid null,
  empresa_id uuid null,
  constraint actividades_consumidores_pkey primary key (id),
  constraint actividades_consumidores_consumidor_id_fkey foreign KEY (consumidor_id) references consumidores (id) on delete CASCADE,
  constraint actividades_consumidores_empresa_id_fkey foreign KEY (empresa_id) references empresas (id)
) TABLESPACE pg_default;

create index IF not exists idx_act_consumidor_id_fecha on public.actividades_consumidores using btree (consumidor_id, fecha desc) TABLESPACE pg_default;

create trigger trg_bump_ultima_actividad_consumidor
after INSERT on actividades_consumidores for EACH row
execute FUNCTION bump_ultima_actividad_consumidor ();

create trigger trg_fill_activity_user_consum BEFORE INSERT on actividades_consumidores for EACH row
execute FUNCTION fill_activity_user ();

create table public.actividades_repartidores (
  id serial not null,
  created_at timestamp with time zone null default now(),
  repartidor_id integer null,
  usuario text null,
  tipo text null,
  detalle text null,
  fecha_accion timestamp with time zone null default now(),
  empresa_id uuid not null,
  constraint actividades_repartidores_pkey primary key (id),
  constraint actividades_repartidores_empresa_id_fkey foreign KEY (empresa_id) references empresas (id),
  constraint actividades_repartidores_repartidor_id_fkey foreign KEY (repartidor_id) references repartidores (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.audit_logs (
  id uuid not null default extensions.uuid_generate_v4 (),
  table_name text not null,
  record_id text not null,
  action_type text not null,
  old_data jsonb null,
  new_data jsonb null,
  changed_by uuid null default auth.uid (),
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint audit_logs_pkey primary key (id),
  constraint audit_logs_changed_by_fkey foreign KEY (changed_by) references usuarios (id)
) TABLESPACE pg_default;

create table public.calificaciones (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  created_by uuid null,
  cliente_id bigint null,
  nombre_local text null,
  puntaje integer null,
  aspecto text null,
  comentario text null,
  estado text null default 'Nuevo'::text,
  atendido_por text null,
  constraint calificaciones_pkey primary key (id),
  constraint calificaciones_cliente_id_fkey foreign KEY (cliente_id) references clientes (id) on delete set null,
  constraint calificaciones_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint calificaciones_puntaje_check check (
    (
      (puntaje >= 1)
      and (puntaje <= 5)
    )
  )
) TABLESPACE pg_default;

create table public.clientes (
  id bigserial not null,
  nombre text not null,
  telefono text null,
  rubro text not null default 'Sin definir'::text,
  estado public.estado_cliente not null default '1 - Cliente relevado'::estado_cliente,
  fecha_proximo_contacto date null,
  notas text null,
  activo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  hora_proximo_contacto time without time zone null,
  responsable text null,
  direccion text null,
  ultima_actividad timestamp with time zone null,
  lat double precision null,
  lng double precision null,
  apellido text null,
  mail text null,
  fecha_contacto date null,
  responsable_id uuid null,
  nombre_local text null,
  cuit text null,
  horarios_atencion text null,
  venta_digital boolean null default false,
  venta_digital_cual text null,
  creado_por text null,
  interes text null,
  estilo_contacto text null default ''::text,
  status_history jsonb null default '[]'::jsonb,
  status_date timestamp with time zone null default now(),
  visitas integer null default 0,
  situacion text null default 'sin comunicacion nueva'::text,
  tipo_contacto text null default 'Visita Presencial'::text,
  activador_cierre text null,
  constraint clientes_pkey primary key (id),
  constraint clientes_telefono_key unique (telefono),
  constraint clientes_responsable_id_fkey foreign KEY (responsable_id) references usuarios (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_clientes_ultima_actividad on public.clientes using btree (ultima_actividad desc nulls last) TABLESPACE pg_default;

create index IF not exists idx_clientes_fecha_proximo_contacto on public.clientes using btree (fecha_proximo_contacto) TABLESPACE pg_default;

create index IF not exists idx_clientes_estado on public.clientes using btree (estado) TABLESPACE pg_default;

create index IF not exists idx_clientes_rubro on public.clientes using btree (rubro) TABLESPACE pg_default;

create index IF not exists idx_clientes_responsable on public.clientes using btree (responsable) TABLESPACE pg_default;

create index IF not exists idx_clientes_activo on public.clientes using btree (activo) TABLESPACE pg_default;

create index IF not exists idx_clientes_responsable_id on public.clientes using btree (responsable_id) TABLESPACE pg_default;

create index IF not exists clientes_telefono_idx on public.clientes using btree (telefono) TABLESPACE pg_default;

create index IF not exists clientes_nombre_idx on public.clientes using btree (nombre) TABLESPACE pg_default;

create index IF not exists clientes_lat_lng_idx on public.clientes using btree (lat, lng) TABLESPACE pg_default;

create unique INDEX IF not exists clientes_mail_unique on public.clientes using btree (mail) TABLESPACE pg_default
where
  (mail is not null);

create unique INDEX IF not exists clientes_telefono_unique on public.clientes using btree (telefono) TABLESPACE pg_default
where
  (telefono is not null);

create index IF not exists idx_clientes_agenda on public.clientes using btree (activo, fecha_proximo_contacto) TABLESPACE pg_default;

create index IF not exists idx_clientes_activo_responsable on public.clientes using btree (activo, responsable) TABLESPACE pg_default;

create index IF not exists idx_clientes_created_at on public.clientes using btree (created_at desc) TABLESPACE pg_default;

create trigger audit_clientes_changes
after INSERT
or DELETE
or
update on clientes for EACH row
execute FUNCTION process_audit_log ();

create trigger clientes_set_updated_at BEFORE
update on clientes for EACH row
execute FUNCTION set_updated_at ();

create trigger tr_auto_insert_ec_legacy
after INSERT on clientes for EACH row
execute FUNCTION auto_insert_empresa_cliente ();

create table public.consumidores (
  id bigserial not null,
  activo boolean not null default true,
  nombre text not null,
  telefono text null,
  mail text null,
  localidad text null,
  barrio text null,
  edad integer null,
  genero text null,
  estado text not null default 'Lead'::text,
  responsable text null,
  fecha_proximo_contacto date null,
  hora_proximo_contacto time without time zone null,
  notas text null,
  ultima_actividad timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  empresa_id uuid null,
  constraint consumidores_pkey primary key (id),
  constraint consumidores_empresa_id_fkey foreign KEY (empresa_id) references empresas (id)
) TABLESPACE pg_default;

create index IF not exists idx_consumidores_activo on public.consumidores using btree (activo) TABLESPACE pg_default;

create index IF not exists idx_consumidores_estado on public.consumidores using btree (estado) TABLESPACE pg_default;

create index IF not exists idx_consumidores_responsable on public.consumidores using btree (responsable) TABLESPACE pg_default;

create index IF not exists idx_consumidores_fecha_prox on public.consumidores using btree (fecha_proximo_contacto) TABLESPACE pg_default;

create index IF not exists idx_consumidores_ultima_actividad on public.consumidores using btree (ultima_actividad) TABLESPACE pg_default;

create index IF not exists idx_consumidores_created_at on public.consumidores using btree (created_at desc) TABLESPACE pg_default;

create table public.empresa_cliente (
  id uuid not null default gen_random_uuid (),
  empresa_id uuid null,
  cliente_id bigint null,
  estado text null,
  rubro text null,
  responsable text null,
  situacion text null,
  notas text null,
  estilo_contacto text null,
  interes text null,
  tipo_contacto text null,
  venta_digital boolean null default false,
  venta_digital_cual text null,
  fecha_proximo_contacto text null,
  hora_proximo_contacto text null,
  creado_por text null,
  activador_cierre text null,
  visitas integer null default 0,
  ultima_actividad timestamp with time zone null,
  activo boolean null default true,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint empresa_cliente_pkey primary key (id),
  constraint empresa_cliente_empresa_id_cliente_id_key unique (empresa_id, cliente_id),
  constraint empresa_cliente_cliente_id_fkey foreign KEY (cliente_id) references clientes (id) on delete CASCADE,
  constraint empresa_cliente_empresa_id_fkey foreign KEY (empresa_id) references empresas (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger audit_empresa_cliente_changes
after INSERT
or DELETE
or
update on empresa_cliente for EACH row
execute FUNCTION process_audit_log ();

create trigger tr_update_updated_at_empresa_cliente BEFORE
update on empresa_cliente for EACH row
execute FUNCTION update_updated_at_column ();

create table public.empresa_permisos_pagina (
  id uuid not null default gen_random_uuid (),
  empresa_id uuid null,
  pagina text not null,
  habilitada boolean null default false,
  roles_permitidos text[] null default array[]::text[],
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint empresa_permisos_pagina_pkey primary key (id),
  constraint empresa_permisos_pagina_empresa_id_pagina_key unique (empresa_id, pagina),
  constraint empresa_permisos_pagina_empresa_id_fkey foreign KEY (empresa_id) references empresas (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.empresa_usuario (
  id uuid not null default gen_random_uuid (),
  empresa_id uuid null,
  usuario_email text not null,
  role text not null default 'activador'::text,
  created_at timestamp with time zone null default now(),
  constraint empresa_usuario_pkey primary key (id),
  constraint empresa_usuario_empresa_id_usuario_email_key unique (empresa_id, usuario_email),
  constraint empresa_usuario_empresa_id_fkey foreign KEY (empresa_id) references empresas (id) on delete CASCADE,
  constraint fk_empresa_usuario_usuarios foreign KEY (usuario_email) references usuarios (email) on delete CASCADE
) TABLESPACE pg_default;

create table public.empresas (
  id uuid not null default gen_random_uuid (),
  nombre text not null,
  logo_url text null,
  created_at timestamp with time zone null default now(),
  constraint empresas_pkey primary key (id)
) TABLESPACE pg_default;

create table public.eventos (
  id bigint generated by default as identity not null,
  titulo text not null,
  descripcion text null,
  tipo text not null default 'interno'::text,
  responsable text null,
  cliente_id bigint null,
  fecha_inicio timestamp with time zone not null,
  fecha_fin timestamp with time zone null,
  all_day boolean not null default false,
  color text null,
  creado_por text null,
  created_at timestamp with time zone not null default now(),
  usuario text null,
  empresa_id uuid null,
  constraint eventos_pkey primary key (id),
  constraint eventos_cliente_id_fkey foreign KEY (cliente_id) references clientes (id) on delete set null,
  constraint eventos_empresa_id_fkey foreign KEY (empresa_id) references empresas (id)
) TABLESPACE pg_default;

create index IF not exists idx_eventos_cliente_id on public.eventos using btree (cliente_id) TABLESPACE pg_default;

create index IF not exists eventos_fecha_inicio_idx on public.eventos using btree (fecha_inicio) TABLESPACE pg_default;

create index IF not exists eventos_responsable_idx on public.eventos using btree (responsable) TABLESPACE pg_default;

create index IF not exists eventos_tipo_idx on public.eventos using btree (tipo) TABLESPACE pg_default;

create index IF not exists eventos_usuario_idx on public.eventos using btree (usuario) TABLESPACE pg_default;

create table public.eventos_historial (
  id bigint generated always as identity not null,
  evento_id bigint not null,
  comentario text not null,
  usuario_email text null,
  created_at timestamp with time zone null default now(),
  empresa_id uuid null,
  constraint eventos_historial_pkey primary key (id),
  constraint eventos_historial_empresa_id_fkey foreign KEY (empresa_id) references empresas (id),
  constraint eventos_historial_evento_id_fkey foreign KEY (evento_id) references eventos_proveedores (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.eventos_proveedores (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  proveedor_id bigint null,
  tipo text null,
  titulo text not null,
  descripcion text null,
  fecha_inicio timestamp with time zone null,
  fecha_fin timestamp with time zone null,
  fecha_real_cierre timestamp with time zone null,
  estado text null default 'pendiente'::text,
  color text null,
  seccion text null,
  empresa_id uuid null,
  constraint eventos_proveedores_pkey primary key (id),
  constraint eventos_proveedores_empresa_id_fkey foreign KEY (empresa_id) references empresas (id),
  constraint eventos_proveedores_proveedor_id_fkey foreign KEY (proveedor_id) references proveedores (id) on delete CASCADE,
  constraint eventos_proveedores_tipo_check check (
    (
      tipo = any (
        array[
          'pedido'::text,
          'idea'::text,
          'plazo'::text,
          'otro'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table public.eventos_usuarios (
  evento_id bigint not null,
  usuario text not null,
  created_at timestamp with time zone not null default now(),
  constraint eventos_usuarios_pkey primary key (evento_id, usuario),
  constraint eventos_usuarios_evento_id_fkey foreign KEY (evento_id) references eventos (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists eventos_usuarios_usuario_idx on public.eventos_usuarios using btree (usuario) TABLESPACE pg_default;

create index IF not exists eventos_usuarios_evento_idx on public.eventos_usuarios using btree (evento_id) TABLESPACE pg_default;

create table public.invitation_codes (
  id serial not null,
  code text not null,
  is_active boolean null default true,
  created_at timestamp with time zone null default now(),
  constraint invitation_codes_pkey primary key (id),
  constraint invitation_codes_code_key unique (code)
) TABLESPACE pg_default;

create table public.mensajes_chat (
  id uuid not null default extensions.uuid_generate_v4 (),
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  de_usuario text not null,
  para_usuario text not null,
  mensaje text not null,
  leido boolean null default false,
  empresa_id uuid not null,
  constraint mensajes_chat_pkey primary key (id),
  constraint fk_mensajes_chat_de_usuario foreign KEY (de_usuario) references usuarios (email) on delete CASCADE,
  constraint fk_mensajes_chat_para_usuario foreign KEY (para_usuario) references usuarios (email) on delete CASCADE,
  constraint mensajes_chat_empresa_id_fkey foreign KEY (empresa_id) references empresas (id)
) TABLESPACE pg_default;

create table public.proveedores (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  nombre text not null,
  contacto text null,
  telefono text null,
  email text null,
  rubro text null,
  notas text null,
  activo boolean null default true,
  empresa_id uuid null,
  constraint proveedores_pkey primary key (id),
  constraint proveedores_empresa_id_fkey foreign KEY (empresa_id) references empresas (id)
) TABLESPACE pg_default;

create table public.push_subscriptions (
  id serial not null,
  user_email text not null,
  subscription jsonb not null,
  created_at timestamp with time zone null default now(),
  constraint push_subscriptions_pkey primary key (id),
  constraint push_subscriptions_user_email_subscription_key unique (user_email, subscription)
) TABLESPACE pg_default;

create table public.repartidores (
  id serial not null,
  created_at timestamp with time zone null default now(),
  nombre text not null,
  telefono text null,
  email text null,
  direccion text null,
  localidad text null,
  estado text null default 'Documentación sin gestionar'::text,
  responsable text null,
  notas text null,
  telefono_norm text null,
  lat numeric null,
  lng numeric null,
  empresa_id uuid not null,
  constraint repartidores_pkey primary key (id),
  constraint repartidores_telefono_norm_uniq unique (telefono_norm),
  constraint repartidores_empresa_id_fkey foreign KEY (empresa_id) references empresas (id)
) TABLESPACE pg_default;

create trigger audit_repartidores_changes
after INSERT
or DELETE
or
update on repartidores for EACH row
execute FUNCTION process_audit_log ();

create table public.tareas_tablero (
  id uuid not null default extensions.uuid_generate_v4 (),
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  titulo text not null,
  descripcion text null,
  estado text null default 'Pendiente'::text,
  asignado_a text null,
  fecha_vencimiento date null,
  checklist jsonb null default '[]'::jsonb,
  orden integer null default 0,
  empresa_id uuid null,
  constraint tareas_tablero_pkey primary key (id),
  constraint tareas_tablero_empresa_id_fkey foreign KEY (empresa_id) references empresas (id)
) TABLESPACE pg_default;

create table public.temp_consumidores (telefono text null, created_at text null) TABLESPACE pg_default;

create table public.tickets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  nombre text null,
  email text null,
  tipo text null,
  asunto text null,
  mensaje text null,
  estado text null default 'Pendiente'::text,
  telefono text null,
  constraint tickets_pkey primary key (id)
) TABLESPACE pg_default;

create table public.turnos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  usuario_email text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  tipo text not null,
  notas text null,
  creado_por text null,
  empresa_id uuid null,
  constraint turnos_pkey primary key (id),
  constraint turnos_empresa_id_fkey foreign KEY (empresa_id) references empresas (id)
) TABLESPACE pg_default;

create table public.usuarios (
  id uuid not null,
  email text null,
  nombre text not null,
  role text not null default 'user'::text,
  activo boolean not null default true,
  lat double precision null,
  lng double precision null,
  last_seen timestamp with time zone null,
  avatar_emoji text null default '📍'::text,
  constraint usuarios_pkey primary key (id),
  constraint usuarios_email_key unique (email),
  constraint usuarios_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.zones (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  created_by uuid null,
  coordinates jsonb not null,
  color text null default '#ef4444'::text,
  label text null,
  is_deleted boolean null default false,
  scope text null default 'client_map'::text,
  empresa_id uuid null,
  constraint zones_pkey primary key (id),
  constraint zones_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint zones_empresa_id_fkey foreign KEY (empresa_id) references empresas (id)
) TABLESPACE pg_default;

create index IF not exists idx_zones_scope on public.zones using btree (scope) TABLESPACE pg_default;


BEGIN
    INSERT INTO empresa_cliente (
        empresa_id,
        cliente_id,
        estado,
        situacion,
        responsable,
        tipo_contacto,
        creado_por,
        activo,A
        created_at,
        updated_at
    ) VALUES (
        '302444cf-9e6b-4127-b018-6c0d1972b276'::uuid, -- ID de PickingUp
        NEW.id,
        COALESCE(NEW.estado, '1 - Cliente relevado'),
        'sin comunicacion nueva',
        COALESCE(NEW.creado_por, 'Sistema'),
        'Visita Presencial',
        COALESCE(NEW.creado_por, 'Sistema'),
        true,
        COALESCE(NEW.created_at, NOW()),
        COALESCE(NEW.updated_at, NOW())
    )
    ON CONFLICT (empresa_id, cliente_id) DO NOTHING;
    
    RETURN NEW;
END;


begin
  update public.clientes
  set ultima_actividad = now()
  where id = new.cliente_id;

  return new;
end;


begin
  update public.consumidores
  set ultima_actividad = now()
  where id = new.consumidor_id;

  return new;
end;


BEGIN
    RETURN QUERY
    SELECT
        ec.id AS ec_id,
        ec.cliente_id,
        ec.empresa_id,
        ec.estado,
        ec.rubro,
        ec.responsable,
        ec.situacion,
        ec.notas,
        ec.estilo_contacto,
        ec.interes,
        ec.tipo_contacto,
        ec.venta_digital,
        ec.venta_digital_cual,
        ec.fecha_proximo_contacto,
        ec.hora_proximo_contacto,
        ec.creado_por,
        ec.activador_cierre,
        ec.visitas,
        ec.ultima_actividad,
        ec.activo,
        ec.created_at AS ec_created_at,
        ec.updated_at AS ec_updated_at,
        c.nombre,
        c.nombre_local,
        c.telefono,
        c.direccion,
        c.mail,
        c.cuit,
        c.lat,
        c.lng,
        c.created_at AS c_created_at
    FROM empresa_cliente ec
    JOIN clientes c ON c.id = ec.cliente_id
    WHERE ec.empresa_id = p_empresa_id
      AND ec.activo = true
      AND (p_nombre IS NULL OR c.nombre ILIKE '%' || p_nombre || '%' OR c.nombre_local ILIKE '%' || p_nombre || '%')
      AND (p_telefono IS NULL OR c.telefono ILIKE '%' || p_telefono || '%')
      AND (p_direccion IS NULL OR c.direccion ILIKE '%' || p_direccion || '%')
      AND (p_estado IS NULL OR ec.estado = p_estado)
      AND (p_situacion IS NULL OR ec.situacion = p_situacion)
      AND (p_tipo_contacto IS NULL OR ec.tipo_contacto = p_tipo_contacto)
      AND (p_responsable IS NULL OR ec.responsable = p_responsable)
      AND (p_rubro IS NULL OR ec.rubro = p_rubro)
      AND (p_interes IS NULL OR ec.interes = p_interes)
      AND (p_estilo IS NULL OR ec.estilo_contacto = p_estilo)
      AND (p_creado_desde IS NULL OR c.created_at >= (p_creado_desde || ' 00:00:00')::TIMESTAMPTZ)
      AND (p_creado_hasta IS NULL OR c.created_at <= (p_creado_hasta || ' 23:59:59')::TIMESTAMPTZ)
    ORDER BY 
        CASE WHEN p_sort_by = 'updated' THEN ec.updated_at END DESC,
        CASE WHEN p_sort_by = 'recent' THEN ec.created_at END DESC,
        CASE WHEN p_sort_by = 'oldest' THEN ec.created_at END ASC,
        CASE WHEN p_sort_by = 'az' THEN c.nombre_local END ASC,
        CASE WHEN p_sort_by = 'za' THEN c.nombre_local END DESC,
        CASE WHEN p_sort_by = 'activity_desc' THEN ec.ultima_actividad END DESC NULLS LAST,
        CASE WHEN p_sort_by = 'activity_asc' THEN ec.ultima_actividad END ASC NULLS FIRST,
        -- Fallback: siempre creacion desc si no coincide nada
        ec.created_at DESC
    LIMIT p_limit OFFSET p_offset;
END;


BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.invitation_codes
    WHERE code = lookup_code AND is_active = true
  );
END;


DECLARE
    new_id UUID;
    v_emp_id UUID;
BEGIN
    -- Verificación de seguridad: ¿Viene el ID de empresa?
    IF datos->>'p_empresa_id' IS NULL THEN
        RAISE EXCEPTION 'ID de empresa faltante (p_empresa_id). JSON recibido: %', datos;
    END IF;

    -- Intentar convertir el ID de empresa, si falla daremos un error claro
    BEGIN
        v_emp_id := (datos->>'p_empresa_id')::UUID;
    EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION 'El ID de empresa no es un UUID válido: "%". JSON: %', datos->>'p_empresa_id', datos;
    END;

    -- A. Insertar en tabla clientes
    INSERT INTO clientes (
        nombre_local, nombre, direccion, telefono, 
        mail, cuit, lat, lng, creado_por
    )
    VALUES (
        datos->>'p_nombre_local', 
        datos->>'p_nombre', 
        datos->>'p_direccion', 
        datos->>'p_telefono', 
        datos->>'p_mail', 
        datos->>'p_cuit', 
        (datos->>'p_lat')::FLOAT8, 
        (datos->>'p_lng')::FLOAT8, 
        datos->>'p_creado_por'
    )
    RETURNING id INTO new_id;

    -- B. Insertar en empresa_cliente
    INSERT INTO empresa_cliente (
        empresa_id, cliente_id, estado, rubro, responsable, 
        situacion, notas, tipo_contacto, creado_por, activo
    )
    VALUES (
        v_emp_id, 
        new_id, 
        datos->>'p_estado', 
        datos->>'p_rubro', 
        datos->>'p_responsable', 
        datos->>'p_situacion', 
        datos->>'p_notas', 
        datos->>'p_tipo_contacto', 
        datos->>'p_creado_por', 
        true
    );

    RETURN new_id;
END;


DECLARE
    new_id UUID;
    v_emp_id UUID;
    v_creador TEXT;
BEGIN
    -- 1. Extraer y validar ID de empresa
    BEGIN
        v_emp_id := (p_payload->>'p_empresa_id')::UUID;
    EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION 'ID de empresa inválido: %. JSON recibido: %', p_payload->>'p_empresa_id', p_payload;
    END;

    v_creador := p_payload->>'p_creado_por';

    -- 2. Insertar en tabla maestra 'clientes'
    INSERT INTO clientes (
        nombre_local, nombre, direccion, telefono, 
        mail, cuit, lat, lng, creado_por
    )
    VALUES (
        p_payload->>'p_nombre_local', 
        p_payload->>'p_nombre', 
        p_payload->>'p_direccion', 
        p_payload->>'p_telefono', 
        p_payload->>'p_mail', 
        p_payload->>'p_cuit', 
        (p_payload->>'p_lat')::FLOAT8, 
        (p_payload->>'p_lng')::FLOAT8, 
        v_creador
    )
    RETURNING id INTO new_id;

    -- 3. Insertar en tabla de negocio 'empresa_cliente'
    INSERT INTO empresa_cliente (
        empresa_id, cliente_id, estado, rubro, responsable, 
        situacion, notas, tipo_contacto, creado_por, activo
    )
    VALUES (
        v_emp_id, 
        new_id, 
        p_payload->>'p_estado', 
        p_payload->>'p_rubro', 
        p_payload->>'p_responsable', 
        p_payload->>'p_situacion', 
        p_payload->>'p_notas', 
        p_payload->>'p_tipo_contacto', 
        v_creador, 
        true
    );

    RETURN new_id;
END;


DECLARE
    new_id BIGINT;
    v_emp_id UUID;
    v_creador TEXT;
BEGIN
    -- 1. Validar y convertir ID de empresa
    BEGIN
        v_emp_id := (p_payload->>'p_empresa_id')::UUID;
    EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION 'ID de empresa inválido: %. JSON: %', p_payload->>'p_empresa_id', p_payload;
    END;

    v_creador := p_payload->>'p_creado_por';

    -- 2. Insertar en tabla maestra 'clientes' (id es BIGINT)
    INSERT INTO clientes (
        nombre_local, nombre, direccion, telefono, 
        mail, cuit, lat, lng, creado_por,
        created_at, updated_at
    )
    VALUES (
        p_payload->>'p_nombre_local', 
        p_payload->>'p_nombre', 
        p_payload->>'p_direccion', 
        p_payload->>'p_telefono', 
        p_payload->>'p_mail', 
        p_payload->>'p_cuit', 
        (p_payload->>'p_lat')::FLOAT8, 
        (p_payload->>'p_lng')::FLOAT8, 
        v_creador,
        NOW(),
        NOW()
    )
    RETURNING id INTO new_id;

    -- 3. Insertar en tabla de negocio 'empresa_cliente' (cliente_id es BIGINT)
    -- Lo convertimos en UPSERT (ON CONFLICT) para que si el Trigger
    -- "auto_insert" para apps viejas ya lo creó 1 milisegundo antes, 
    -- lo sobreescribimos pacificamente con los datos ricos de esta RPC.
    INSERT INTO empresa_cliente (
        empresa_id, cliente_id, estado, rubro, responsable, 
        situacion, notas, tipo_contacto, creado_por, activo,
        created_at, updated_at
    )
    VALUES (
        v_emp_id, 
        new_id, 
        p_payload->>'p_estado', 
        p_payload->>'p_rubro', 
        p_payload->>'p_responsable', 
        p_payload->>'p_situacion', 
        p_payload->>'p_notas', 
        p_payload->>'p_tipo_contacto', 
        v_creador, 
        true,
        NOW(),
        NOW()
    )
    ON CONFLICT (empresa_id, cliente_id) DO UPDATE SET
        estado = EXCLUDED.estado,
        rubro = EXCLUDED.rubro,
        responsable = EXCLUDED.responsable,
        situacion = EXCLUDED.situacion,
        notas = EXCLUDED.notas,
        tipo_contacto = EXCLUDED.tipo_contacto,
        creado_por = EXCLUDED.creado_por,
        activo = EXCLUDED.activo,
        updated_at = EXCLUDED.updated_at;

    RETURN new_id;
END;


begin
  if new.user_id is null then
    new.user_id := auth.uid();
  end if;

  -- Si no vino "usuario", lo completamos desde public.usuarios (tu display name)
  if new.usuario is null or btrim(new.usuario) = '' then
    select u.nombre into new.usuario
    from public.usuarios u
    where u.id = auth.uid()
    limit 1;

    -- fallback si no hay fila
    if new.usuario is null or btrim(new.usuario) = '' then
      new.usuario := 'Usuario';
    end if;
  end if;

  return new;
end;


BEGIN
    RETURN QUERY 
    SELECT empresa_id 
    FROM public.empresa_usuario 
    WHERE usuario_email = (SELECT auth.jwt() ->> 'email');
END;


begin
  insert into public.usuarios (id, email, nombre, role, activo)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)),
    'user',
    true
  )
  on conflict (id) do update
  set
    email  = excluded.email,
    nombre = excluded.nombre;

  return new;
end;


declare
  v_nombre text;
begin
  v_nombre := coalesce(
    new.raw_user_meta_data->>'nombre',
    new.raw_user_meta_data->>'name',
    split_part(new.email, '@', 1),
    new.email
  );

  insert into public.usuarios (id, email, nombre, role, activo)
  values (new.id, new.email, v_nombre, 'user', true)
  on conflict (id) do update
    set email = excluded.email;

  return new;
end;


  select exists(
    select 1 from public.usuarios u
    where u.id = auth.uid() and u.activo = true
  );


BEGIN
    RETURN EXISTS (
        SELECT 1 FROM usuarios
        WHERE email = auth.email()
        AND LOWER(role) IN ('admin', 'super-admin', 'administrador')
    );
END;


DECLARE
    v_old_data JSONB;
    v_new_data JSONB;
    v_record_id TEXT;
BEGIN
    IF (TG_OP = 'UPDATE') THEN
        v_old_data := to_jsonb(OLD);
        v_new_data := to_jsonb(NEW);
        
        IF v_new_data ? 'id' THEN
            v_record_id := (v_new_data->>'id')::TEXT;
        ELSIF v_new_data ? 'cliente_id' THEN
            v_record_id := (v_new_data->>'cliente_id')::TEXT;
        ELSE
            v_record_id := 'UNKNOWN';
        END IF;

        INSERT INTO public.audit_logs (table_name, record_id, action_type, old_data, new_data)
        VALUES (TG_TABLE_NAME::TEXT, v_record_id, TG_OP, v_old_data, v_new_data);
        
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        v_old_data := to_jsonb(OLD);
        
        IF v_old_data ? 'id' THEN
            v_record_id := (v_old_data->>'id')::TEXT;
        ELSIF v_old_data ? 'cliente_id' THEN
            v_record_id := (v_old_data->>'cliente_id')::TEXT;
        ELSE
            v_record_id := 'UNKNOWN';
        END IF;

        INSERT INTO public.audit_logs (table_name, record_id, action_type, old_data, new_data)
        VALUES (TG_TABLE_NAME::TEXT, v_record_id, TG_OP, v_old_data, NULL);
        
        RETURN OLD;
    ELSIF (TG_OP = 'INSERT') THEN
        v_new_data := to_jsonb(NEW);
        
        IF v_new_data ? 'id' THEN
            v_record_id := (v_new_data->>'id')::TEXT;
        ELSIF v_new_data ? 'cliente_id' THEN
            v_record_id := (v_new_data->>'cliente_id')::TEXT;
        ELSE
            v_record_id := 'UNKNOWN';
        END IF;

        INSERT INTO public.audit_logs (table_name, record_id, action_type, old_data, new_data)
        VALUES (TG_TABLE_NAME::TEXT, v_record_id, TG_OP, NULL, v_new_data);
        
        RETURN NEW;
    END IF;
    
    RETURN NULL;
END;


begin
  if (TG_OP = 'INSERT' or TG_OP = 'UPDATE') then
    update public.clientes
       set ultima_actividad = (
         select max(a.fecha)
         from public.actividades a
         where a.cliente_id = NEW.cliente_id
       )
     where id = NEW.cliente_id;
    return NEW;
  elsif (TG_OP = 'DELETE') then
    update public.clientes
       set ultima_actividad = (
         select max(a.fecha)
         from public.actividades a
         where a.cliente_id = OLD.cliente_id
       )
     where id = OLD.cliente_id;
    return OLD;
  end if;

  return null;
end;


begin
  new.updated_at = now();
  return new;
end;


BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;


BEGIN
  -- Verifica si existe un usuario con ese email Y ese nombre (display_name)
  RETURN EXISTS (
    SELECT 1 FROM auth.users
    WHERE email = check_email
    AND raw_user_meta_data->>'display_name' = check_name
  );
END;
